### ISSUE TITLE
Support for Laravel 9?

### ISSUE THREAD

**Issue by orjanalmen** [sqits/laravel-userstamps#11]
Can you add support for Laravel 9? I think you just need to change the composer.json

**Comment by samuel-ginot** [comment]
Is it possible you could change the composer.json to upgrade laravel to 9 version with your package? Or dou you have another solution? Thanks in advance

**Comment by rschaaphuizen** [comment]
Pull request has been merged. Thanks for the input!

**Comment by samuel-ginot** [comment]
Excuse me but you have modified for laravel 9 in your master branch but you don't have create un new tag version.. So when we make a composer require for your package, we are redirect to your tag. version 0.0.9 which is not with your good composer.json. Can you correct this or create a new tag version? Please . thanks a lot
