### ISSUE TITLE
Packagist version is still only supporting Laravel 8

### ISSUE THREAD

**Issue by Sophist-UK** [sqits/laravel-userstamps#14]
Although this repo has a commit to support Laravel 9, the version on [Packagist](https://packagist.org/packages/sqits/laravel-userstamps) still only  supports up to v8.

**Comment by zamblas** [comment]
You can install the dev-master branch
` composer require sqits/laravel-userstamps:dev-master`

**Comment by Sophist-UK** [comment]
Yup - I worked that out.

**Comment by rschaaphuizen** [comment]
Thanks for noticing the issue, the package is now updated to support laravel 9
