### ISSUE TITLE
uuid not supported

### ISSUE THREAD

**Issue by yuriizee** [sqits/laravel-userstamps#7]
if use uuid type for id, macros has error in registerUserstamps
SQLSTATE[42830]: Invalid foreign key: 7 ERROR:  there is no unique constraint matching given keys for referenced table "users" (SQL: alter table "users" add constraint "users_created_by_foreign" foreign key ("created_by") references "users" ("id") on delete set null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +9 vendor frames
  10  database/migrations/2014_10_12_000000_create_users_table.php:30
      Illuminate\Support\Facades\Facade::__callStatic("create")

      +35 vendor frames
  46  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by rschaaphuizen** [comment]
Do you use a specific package for the uuid, or do you use `$table->uuid()` from Laravel?

**Comment by yuriizee** [comment]
$table->uuid() from Laravel

**Comment by rschaaphuizen** [comment]
Thanks for the information. I'll try to add this feature anytime soon.

**Comment by rschaaphuizen** [comment]
I've added the support for uuid fields in the database in version 0.0.8
