### ISSUE TITLE
Support for Laravel 8?

### ISSUE THREAD

**Issue by orjanalmen** [sqits/laravel-userstamps#8]
Can you add support for Laravel 8? I think you just need to change the composer.json

**Comment by rschaaphuizen** [comment]
Sure, I’ll Make the changes somewhere this week and test is with Laravel 8.

**Comment by Dwingloo** [comment]
Was just gonna ask the same question, laravel 8 support ^^, great thanks @rschaaphuizen

**Comment by rschaaphuizen** [comment]
Support for L8 has been added.
